name: Build Android APK

# این اکشن با هر تغییر در شاخه اصلی اجرا می‌شود
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # برای بیلد اندروید در Flet به Flutter نیاز داریم که این بخش آن را روی سرور گیت‌هاب نصب می‌کند
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Flet
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Build APK
        # این دستور کل پروژه را به فرمت اندروید کامپایل می‌کند
        run: flet build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SNI-Scanner-Android-APK
          # مسیر پیش‌فرض ذخیره فایل‌های APK در Flet
          path: build/apk/*.apk
          retention-days: 7
