name: Build Windows App

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        # نصب پای‌اینستالر برای بیلد گرفتن
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Windows EXE
        # این دستور فایل windows_app.py را به یک فایل اجرایی تمیز تبدیل می‌کند
        run: pyinstaller --noconsole --onefile windows_app.py

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SNI-Scanner-Windows-EXE
          # خروجی در پوشه dist ذخیره می‌شود
          path: dist/*.exe
          retention-days: 7
