name: Build Android APK (Golang + Fyne)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # نسخه پایدار Go

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc libgl1-mesa-dev xorg-dev

      - name: Install Fyne CLI
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Initialize Go Mod
        run: |
          go mod init sniscanner
          go mod tidy

      - name: Build APK
        # این دستور فایل APK را با آیکون پیش‌فرض می‌سازد
        run: ~/go/bin/fyne package -os android -appID com.seramo.sniscanner

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SNI-Scanner-Go-APK
          path: "*.apk"
